### ISSUE TITLE
FileSize should be long, not int

### ISSUE THREAD

**Issue by richardcastle** [ScottIsAFool/LiveSDKHelper#2]
LiveSDKHelper / LiveSDKHelper / SkyDrive / ItemDetails.cs

Within the class, ItemDetails:

[DataMember(Name = "size")]
        public int Size { get; set; }

should be:

[DataMember(Name = "size")]
        public long Size { get; set; }

**Comment by ScottIsAFool** [comment]
Fixed in changeset https://github.com/ScottIsAFool/LiveSDKHelper/commit/76ad8eb408383f3b4d310351e6e69e951e66b52b
